version: '3.8'

services:
  web:
    build:
      context: ./bug_tracker
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py makemigrations
      && python3 manage.py migrate --noinput
      && python3 manage.py collectstatic --noinput
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./test_site:/app/
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./configs/nginx/conf.d/:/etc/nginx/conf.d/
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
