# Generated by Django 4.2.11 on 2024-04-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_admin",
        ),
    ]
