name: deployment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Name of target environment to deploy to.
      branch:
          type: string
          required: true
          description: Name of the branch to be deployed from.

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Deploying ${{ inputs.branch }} branch to ${{ inputs.environment }} via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/bug-tracker-fyp/bug_tracker
            docker compose down --rmi local
            cd ~/
            rm -rf ~/bug-tracker-fyp/
            git clone -b ${{ inputs.branch }} https://github.com/Jharopa/bug-tracker-fyp.git
            cd ~/bug-tracker-fyp/
            echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
            echo "DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}" >> .env
            docker compose up -d --build

      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: Deployment to ${{ inputs.environment }}
          username: GitHub Actions
